### ISSUE TITLE
Add Awesome Journalism

### ISSUE THREAD

**Issue by FourthEstateOrg** [nayafia/microgrants#20]
Awesome Journalism - AwesomeJournalism.org

----
Awesome Journalism is a platform for people and organizations that support and advance the interest of journalism in the world.

Each independent and fully autonomous chapter funds and supports awesome local journalism projects through micro-grants, usually given out monthly.

These micro-grants come out of pockets of the chapter's "trustees" and are given on a no-strings-attached basis to people and groups working on awesome journalism stories and projects.

**Comment by nayafia** [comment]
@FourthEstateOrg Thanks! Added.
