### ISSUE TITLE
Non-financial support offerings?

### ISSUE THREAD

**Issue by stuartpb** [nayafia/microgrants#22]
I read [your announcement on the first round of Helium Grants](https://medium.com/@nayafia/how-to-give-away-5-000-on-the-internet-66cae906ab7e), and this line really resonated with me:

> Finally, a lot of people were looking for accountability. Being selected wasn’t so much about needing money as having someone believe in them. The $5K would signify that their idea was worth pursuing.

This is something I think about a lot. There's a big part of me that feels that the thing my projects are missing to get off the ground isn't money (most of my projects wouldn't cost anything up front, and I feel that I could probably [find a way to monetize them once they're up and running](https://github.com/nayafia/lemonade-stand)), but *recognition*: I've started more than a few projects that have reached viability (like [Plushu][] and [OPWS][]), but they've floundered because I didn't have any way to get anybody else *interested in them*, to a point where I could sustain the interest to keep developing them beyond just an MVP. (Working on a big project that nobody's seeing makes me feel like [Henry Darger][], a poor, isolated custodian who spent his life writing a fifteen-thousand-page manuscript that nobody even knew he was working on until his landlords found it the day before he died.)

[Plushu]: https://github.com/plushu
[OPWS]: https://github.com/opws
[Henry Darger]: https://en.wikipedia.org/wiki/Henry_Darger

I've found myself wishing that there was something like Y Combinator, but without the monetary expectations (on either side): a group of smart, well-connected mentors who can help put its selected applicants in touch with potentially-interested parties, can help them write press releases and things like that, and, most importantly, can keep tabs on their progress, and give them encouragement and/or blunt feedback (when called for) to help point them in the right direction when they're stuck.

Do you (or anybody else reading this issue) know of any groups like this? If not, how might such a group be founded? Would it maybe make sense to keep a list of "non-monetary grants" like this in this repository (possibly in a separate .md file from the README)?

**Comment by stuartpb** [comment]
After thinking about this a little bit last night, it occurred to me that the role I'm describing sounds pretty similar to that of a *[producer][]* in other creative fields (particularly in [music][Record producer]).

I'm thinking of putting together a project/repo some time tonight as a hub for "Requests for Producers", where hackers can find somebody who might be willing to [champion][TC39] the projects and initiatives they care about - and vice versa: a place where desultory hackers and/or restless project managers might find a project they can contribute to in a largely hands-off capacity.

[Producer]: https://en.wikipedia.org/wiki/Producer
[Record producer]: https://en.wikipedia.org/wiki/Record_producer
[TC39]: https://tc39.github.io/process-document/

**Comment by nayafia** [comment]
Hi! Thanks for the thoughtful ideas. It reminds me a bit of what [Assembly](http://www.assemblymade.com/) was trying to do. Also the [YC Fellowship](https://blog.ycombinator.com/yc-fellowship/), though I think it's been discontinued. And there's [Pioneer](https://pioneer.app/), which I think is positioned as a platform/community vs. a pure grant program for precisely these reasons.

Those are the first few that come to mind; I'm sure there are others. It'd be great to curate a list like this, though I think it's out of scope for this repo. If you start a list, comment back in here, maybe it'd make sense to link to it!
