### ISSUE TITLE
Uncharted Journalism Fund is shutdown as of March 15th 

### ISSUE THREAD

**Issue by sidtechnical** [nayafia/microgrants#42]
As per their official notice, [the Uncharted Journalism Fund has been shutdown](https://unchartedjournalism.org/uncharted-journalism-fund-experiment-complete-lessons-learned-5f53473a92c3). Hence, it should be added to  _grant programs are no longer active, but you might find them useful to read about as case studies_.

**Comment by nayafia** [comment]
@sidtechnical thanks for flagging! Updated in https://github.com/nayafia/microgrants/commit/458f636c2a677ed6aa5f28e3dfdfef62ee4c03d2.
