### ISSUE TITLE
Consider setting up github pages

### ISSUE THREAD

**Issue by ignoramous** [nayafia/microgrants#52]
Setting up GitHub pages (which, btw, optionally supports [adding custom domains](https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/managing-a-custom-domain-for-your-github-pages-site#configuring-a-subdomain), say `microgrants.dev`, for free) is pretty straight-forward, and you can see what the result looks like here: https://ignoramous.github.io/microgrants/

Steps ([see also](https://pages.github.com/)):
1. Click on project's Settings tab.
  a. Under `Options` (left nav), go to the `GitHub Pages` section
  b. Enable it for the `master` branch.
  c. Choose a theme.
  d. Commit (*without* committing `index.md`).
2. Stylize `README.md` as appropriate.
3. Wait for the deployment to complete (See the new `Environment` section on the GitHub project's front page), once that's done, the webpage should be up and running.

**Comment by nayafia** [comment]
Thanks for the suggestion! I use GitHub Pages for my personal website :blush:

I started this repo a long time ago (nearly 4 years ago!) and don't plan to actively develop it beyond minimum PR review. (Not sure where all the recent traffic has come from?) But if you'd like to maintain a web version, you're of course welcome to.

**Comment by ignoramous** [comment]
Sad.

The recent traffic is likely from hacker news: https://news.ycombinator.com/item?id=25649363

Alternatively, you could look for top referrers in the _Insights_ tab of the project (only visible to project owners).
