### ISSUE TITLE
consider adding this website that helps manage microgrants for students

### ISSUE THREAD

**Issue by ademidun** [nayafia/microgrants#54]
Perhaps you could add my website,  [Atila](https://atila.ca/)  to this repo as a resource for people who want to start a microgrant but need a tool to help them manage the logistics and they don't have to worry about all the admin work.

I built Atila to makes it easy for more people to start and manage microgrants for students. 

So essentially [Atila handles all the logistical stuff](http://atila.ca/start) like helping the sponsor find students to apply, ranking and scoring applications, messaging finalists and winners, handling the payment etc.

This allows the sponsor to just focus on funding the microgrant, reviewing the applications and picking the winner.

I call it a scholarship but actually I just realized that a scholarship is basically a microgrant for students.

For example, here is a [microgrant we have for any student working on a side project](https://atila.ca/scholarship/atila-continuous-learning-scholarship-j11gu8k5).

**Comment by ademidun** [comment]
Changed the title to be more polite 😄 

![Screen Shot 2021-03-05 at 11 02 13 AM](https://user-images.githubusercontent.com/9806858/110140611-4625fa00-7da2-11eb-9551-9f1bd35296b5.png)

**Comment by nayafia** [comment]
thanks! this is cool, but doesn't quite fit the list of other microgrants.
